### ISSUE TITLE
Debugging old demos in move.py

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/demos#35]
rosrun move_demo move.py rotate 45
[INFO] [1655748432.412112]: Waiting for move service to be available
[ERROR] [1655748442.431999]: Move service not available
[INFO] [1655748442.441959]: Rotating 45.000000 degrees
[ERROR] [1655748442.451887]: Move service not available
Exception in thread /tf:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_pubsub.py", line 185, in robust_connect_subscriber
    conn.receive_loop(receive_cb)	    
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in receive_loop
    self.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 858, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by anfederman** [comment]
ubuntu@ubuntu:~/catkin_ws/src/demos/move_demo$ rosrun move_demo move.py rotate 90
[INFO] [1655997098.363798]: Waiting for move service to be available
[ERROR] [1655997108.397973]: Move service not available
[INFO] [1655997108.421191]: Rotating 90.000000 degrees
[ERROR] [1655997108.446851]: Move service not available
 
So this is a full stack running aruco_detect, fiducial_slam, lslidar:  but no move topics are being published.

**Comment by anfederman** [comment]
here is complete error, conflict with lslidar:

[ WARN] [1656002694.813631895]: Parameter change detected
Warning: TF_OLD_DATA ignoring data from the past (Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained) for frame laser at time 1656002360.547505 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
[ INFO] [1656002695.018280824]: Move Basic ready
[move_basic-1] process has died [pid 4105, exit code -11, cmd /opt/ros/noetic/lib/move_basic/move_basic __name:=move_basic __log:=/home/ubuntu/.ros/log/fa1e9eea-f312-11ec-899f-6b8240a5d48c/move_basic-1.log].
log file: /home/ubuntu/.ros/log/fa1e9eea-f312-11ec-899f-6b8240a5d48c/move_basic-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
[ WARN] [1656002694.813631895]: Parameter change detected
Warning: TF_OLD_DATA ignoring data from the past (Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained) for frame laser at time 1656002360.547505 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
[ INFO] [1656002695.018280824]: Move Basic ready
[move_basic-1] process has died [pid 4105, exit code -11, cmd /opt/ros/noetic/lib/move_basic/move_basic __name:=move_basic __log:=/home/ubuntu/.ros/log/fa1e9eea-f312-11ec-899f-6b8240a5d48c/move_basic-1.log].
log file: /home/ubuntu/.ros/log/fa1e9eea-f312-11ec-899f-6b8240a5d48c/move_basic-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
but:
ubuntu@ubuntu:~$ rostopic list|grep move
/move_base/cancel
/move_base/feedback
/move_base/goal
/move_base/result
/move_base/status
/move_base/stop
/move_base_simple/goal
/move_basic/parameter_descriptions
/move_basic/parameter_updates

**Comment by anfederman** [comment]
still getting error move service unavailable

**Comment by anfederman** [comment]
OK  turning the laser driver off and launching move_basic

rosrun move_demo move.py rotate 90
[INFO] [1656003419.164546]: Waiting for move service to be available
[INFO] [1656003419.568932]: Rotating 90.000000 degrees
[INFO][1656003419.602981]: Success
except robot didn't move on rotate,

did move forward.

on rotate, no cmd_vel were issued.
